# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

# Get the private IP address from the environment, to allow a developer to
# override the default.
private_ip = ENV['SHIB_TEST_VM_IP'] || "192.168.33.10"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Every Vagrant virtual environment requires a box to build off of.
  # This box is provided by Puppet Labs; see http://puppet-vagrant-boxes.puppetlabs.com/ 
  config.vm.box = "centos510-x64"
  config.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/centos-510-x64-virtualbox-puppet.box"

  # Increase the amount of RAM
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
  end
  
  # Share an additional folder to the guest VM. This directory contains
  # scripts that are useful for multiple Vagrant configurations.
  config.vm.synced_folder "../vagrant_shared", "/vagrant_shared"
  
  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network "private_network", ip: private_ip
    
  # Install and configure necessary components
  config.vm.provision :shell, path: "../vagrant_shared/oracle_jdk/install_jdk.sh"
  config.vm.provision "shell", path: "vm-setup.sh"
end
